trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

variables:
 build_path: mobile-release/mobile-app-qa
 publish_path_android: mobile-release/mobile-app-qa/platforms/android/app/build/outputs/apk/debug/app-debug.apk
 publish_path_ios: mobile-release/mobile-app-qa/platforms/ios/build/Release-iphoneos/CMF QA.ipa
 FIREBASE_SERVICE_ACCOUNT_JSON: mobile-release/google-services.json

stages:
- stage: BuildAndDistribute
  jobs:
  - job: BuildAndDistribute
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cat $(FIREBASE_SERVICE_ACCOUNT_JSON)
      displayName: 'Print JSON Contents'
    - task: Npm@1
      inputs:
        command: custom
        customCommand: install -g firebase-tools
      displayName: "Install firebase-tools"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          firebase --version
      displayName: "Print firebase version"
    - bash: | 
        export GOOGLE_APPLICATION_CREDENTIALS=$(FIREBASE_SERVICE_ACCOUNT_JSON)
        echo $GOOGLE_APPLICATION_CREDENTIALS
        firebase appdistribution:distribute $(publish_path_android) --release-notes "Nueva versión" --app 1:401768650475:android:037e6d5a12bf46698a10ae --debug
        displayName: "Setting GOOGLE_APPLICATION_CREDENTIALS env"