trigger:
- main

variables:
 build_path: mobile-release/mobile-app-qa
 publish_path_android: mobile-release/mobile-app-qa/platforms/android/app/build/outputs/apk/debug/app-debug.apk
 publish_path_ios: mobile-release/mobile-app-qa/platforms/ios/build/Release-iphoneos/CMF QA.ipa

stages:
- stage: BuildAndDistribute
  jobs:
  - job: BuildAndDistribute
    pool:
     name: Default
     demands: Agent.Name -equals Dense
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get Firebase Service Account JSON'
      inputs:
        azureSubscription: 'e7f8df62-f46c-40e2-862b-62c2173782fd'
        keyVaultName: 'firebase-dsitribution'
        secretName: 'firebase-service-account'
        secretValue: '$(FIREBASE_SERVICE_ACCOUNT_JSON)'
       
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          nvm use 22
      displayName: "use node 22"
    - task: Npm@1
      inputs:
        command: custom
        customCommand: install -g firebase-tools
      displayName: "Install firebase-tools"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          firebase --version
      displayName: "Print firebase version"
    - bash: | 
        export GOOGLE_APPLICATION_CREDENTIALS=$(FIREBASE_SERVICE_ACCOUNT_JSON)
        echo $GOOGLE_APPLICATION_CREDENTIALS
        firebase appdistribution:distribute $(publish_path_android) --release-notes "Nueva versión" --app 1:401768650475:android:037e6d5a12bf46698a10ae --debug
        displayName: "Setting GOOGLE_APPLICATION_CREDENTIALS env"